{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "bugvis-frontend",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-control",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-model",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-frontend-0.1.jar",
          "url": "bugvis-frontend-0.1.jar",
          "size": 122308,
          "sha512": "1d673917750a8e7adcbf96c7bafc1665d7884699801e9080003d234964f2b5e937b4032fba96630085d6cd03c3831933e9db1aeab73f8f80f509ea9c265c744b",
          "sha256": "097129e9bbf9d4ed8f8d21ff089a72733d67f46fde93b66dee83661d9d26730f",
          "sha1": "c0b8fa340a8ddc4c82d5a5774413213ec1bcad07",
          "md5": "a3240fabd5cb1a054941e67424e5d369"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fifesoft",
          "module": "rsyntaxtextarea",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.37"
          }
        },
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-control",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-model",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-frontend-0.1.jar",
          "url": "bugvis-frontend-0.1.jar",
          "size": 122308,
          "sha512": "1d673917750a8e7adcbf96c7bafc1665d7884699801e9080003d234964f2b5e937b4032fba96630085d6cd03c3831933e9db1aeab73f8f80f509ea9c265c744b",
          "sha256": "097129e9bbf9d4ed8f8d21ff089a72733d67f46fde93b66dee83661d9d26730f",
          "sha1": "c0b8fa340a8ddc4c82d5a5774413213ec1bcad07",
          "md5": "a3240fabd5cb1a054941e67424e5d369"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-frontend-0.1-javadoc.jar",
          "url": "bugvis-frontend-0.1-javadoc.jar",
          "size": 348926,
          "sha512": "36a1c16b98c5270334004f8dbb7ac3c4be54a07c3167f38bca2341ccc5d1c25ad64552f43145e286cd8ed1b0309a242fcee6e859278251a7546df93de46f35db",
          "sha256": "d0ab3097bc16c1f934dcf93d2be9c6d0d61df0ecc1537ac205c52d5e2b9bf5c9",
          "sha1": "e97a9983053c896e316036e6b20d53f8e9151846",
          "md5": "3e1b02ef077a63330654a42e39b3f757"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-frontend-0.1-sources.jar",
          "url": "bugvis-frontend-0.1-sources.jar",
          "size": 54626,
          "sha512": "b4de593e6ef0c17d75fecb32f11e957342a0257bfbe6eada7d118d846fae7688aca44674190db647d6f88a83a07a2ca807b61e35cb7157da66be72ec9807bb39",
          "sha256": "86f9ea923efb0189193c86dbcdfbbcc1aabad2325e4b73db3e7c3b1775a6d2aa",
          "sha1": "9d5a5aa9245f983c34e5fdafac8ea06dba090a53",
          "md5": "34d96d56b5752651bcbcb0185fcb0e97"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-frontend-0.1-all.jar",
          "url": "bugvis-frontend-0.1-all.jar",
          "size": 9581572,
          "sha512": "6cf43c3549eac935f8690dc3fda446cddffcca04d684802a94e56418e8c27b96268231ac52d229bb580554b3b2cb9b6464827c40008e0f666d7d0994ff3b81b9",
          "sha256": "2320ee17be993deb3271aa2813f67f9d5cb773e029dbb147b101b80f5d066be2",
          "sha1": "edec53136e3b79dabc82d832fc1e636dccfcc951",
          "md5": "783dba594715e754b7f3cc8e1eb429fa"
        }
      ]
    }
  ]
}
