{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis.core",
    "module": "bugvis-instr-api",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bugvis-instr-api-0.1.jar",
          "url": "bugvis-instr-api-0.1.jar",
          "size": 27903,
          "sha512": "e22d0e4d68dca9aa3a9387a4d8f6db13fd6fd9f8effbc91fd682e23087dc42fbf1c8f6ee12eb2418aca1e9fd6c9ecee0f89820a03bece91bca788f6c98935840",
          "sha256": "c17edfbceee5fb76c4cff97d88d11f592483852d6742f889340d980c3e4cc464",
          "sha1": "609ba4c923fdda9cdf3072c3803f618271bab7b6",
          "md5": "3a5d4c6c234a45a3711ed30d4d291c31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-instr-api-0.1.jar",
          "url": "bugvis-instr-api-0.1.jar",
          "size": 27903,
          "sha512": "e22d0e4d68dca9aa3a9387a4d8f6db13fd6fd9f8effbc91fd682e23087dc42fbf1c8f6ee12eb2418aca1e9fd6c9ecee0f89820a03bece91bca788f6c98935840",
          "sha256": "c17edfbceee5fb76c4cff97d88d11f592483852d6742f889340d980c3e4cc464",
          "sha1": "609ba4c923fdda9cdf3072c3803f618271bab7b6",
          "md5": "3a5d4c6c234a45a3711ed30d4d291c31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-instr-api-0.1-sources.jar",
          "url": "bugvis-instr-api-0.1-sources.jar",
          "size": 18001,
          "sha512": "09258903efe4f70b7988dc313936a7f3219592c990be2d4948b8be4fd04c11f003086de2ba65ea06ba393c3fea73207d43db1ec19b47981ffbbfe9259ec187b8",
          "sha256": "45d14e298d28be4b917d5dcefb75dc6deb638bce1ae9936cb8372595526e01cb",
          "sha1": "39990f2552a6c441bd141b751ddb14bafe66ae73",
          "md5": "944cd2845054c57697e70d83101dda79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-instr-api-0.1-javadoc.jar",
          "url": "bugvis-instr-api-0.1-javadoc.jar",
          "size": 195544,
          "sha512": "eb7f9ed7c3a47dadc6a8efbf41b3796d2f232ded53d2f2ab58c0a62b2e6f04f941a640c8187ecc2034fe4a4a11ecb2583d8ff1de38ab0a486c73cc26577fc634",
          "sha256": "69605a6f5fa55cea56c9fae34bc9c36884f2d19a954e120c446e2ebf5c51ca44",
          "sha1": "08a57cc5c44514739c6dfb0e9b05f58ba3a6a342",
          "md5": "552b8c1b677d4f2e4aa61cffddc81479"
        }
      ]
    }
  ]
}
