{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis.plugins",
    "module": "list-visualization",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "list-visualization-0.1.jar",
          "url": "list-visualization-0.1.jar",
          "size": 12666,
          "sha512": "6442523b7cf4a77d2690c55f50941f3eff0632c55b4b58deebcbdabc41d3c22b133b1a30fac6d831951ac528998536140a03a17e1ba193ef16ddc09a1a82811d",
          "sha256": "21c15d6afb6e2aeeab742a0d60cd87e62377d58380d535693973b30cce0b892c",
          "sha1": "6f269a15854c52f190d03b70cf1d8152077b7923",
          "md5": "dd764cb8b7493e79a8eba6a4bd9e33d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis.core",
          "module": "bugvis-frontend",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "list-visualization-0.1.jar",
          "url": "list-visualization-0.1.jar",
          "size": 12666,
          "sha512": "6442523b7cf4a77d2690c55f50941f3eff0632c55b4b58deebcbdabc41d3c22b133b1a30fac6d831951ac528998536140a03a17e1ba193ef16ddc09a1a82811d",
          "sha256": "21c15d6afb6e2aeeab742a0d60cd87e62377d58380d535693973b30cce0b892c",
          "sha1": "6f269a15854c52f190d03b70cf1d8152077b7923",
          "md5": "dd764cb8b7493e79a8eba6a4bd9e33d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "list-visualization-0.1-javadoc.jar",
          "url": "list-visualization-0.1-javadoc.jar",
          "size": 118928,
          "sha512": "43f2f817603ad7106045c0d197582f03267a4102496b3b6381ca6bed6b3ea66bb5ec558958d7c67be63b050f027912511694f0ded0c0b0f61151eddbb9bea882",
          "sha256": "3dc8d2683d67f0b23daaceaec1edb16599d4adef9302e74b1f76dbb7877bd1a1",
          "sha1": "76696797a5b73ca85161bcd53ea878b7a1dec9a7",
          "md5": "2f8d52791fb6678569379950d9203f20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "list-visualization-0.1-sources.jar",
          "url": "list-visualization-0.1-sources.jar",
          "size": 6139,
          "sha512": "a891e532cef1df4571d4db9f1b9c54e15d09a3920d326b0c3f37a25b960f9e48337203a44a559d986beb5dffc6ee9bcc6b4918ef7588d70202ca9efa57f0528e",
          "sha256": "0a8d2db6d7c94d6d2e3e8aeda976f753e2047baafb5f70120d02e29cebee0955",
          "sha1": "be4362f5da872434a27107d647e2f3a4fea97f91",
          "md5": "e47048885d2754c64903a27e6c4a5357"
        }
      ]
    }
  ]
}
