{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis.plugins",
    "module": "list-visualization",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "list-visualization-0.1.jar",
          "url": "list-visualization-0.1.jar",
          "size": 12962,
          "sha512": "321536a2e81a27425041f6b5a448050377e80d2b529f985f59fc484c532ca369eff299209cd2108327d7424185a360bf249a015b356620d8c1be789157608c1f",
          "sha256": "ee38d4c3d50e91de0883fb2c94eacd524500cfd15ad337b4a2b582744db7f95e",
          "sha1": "ae0707407f9a019c013704f0e45f70402c2f43cb",
          "md5": "820ed92e358aa251bef6e4569b9d41a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis.core",
          "module": "bugvis-frontend",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "list-visualization-0.1.jar",
          "url": "list-visualization-0.1.jar",
          "size": 12962,
          "sha512": "321536a2e81a27425041f6b5a448050377e80d2b529f985f59fc484c532ca369eff299209cd2108327d7424185a360bf249a015b356620d8c1be789157608c1f",
          "sha256": "ee38d4c3d50e91de0883fb2c94eacd524500cfd15ad337b4a2b582744db7f95e",
          "sha1": "ae0707407f9a019c013704f0e45f70402c2f43cb",
          "md5": "820ed92e358aa251bef6e4569b9d41a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "list-visualization-0.1-javadoc.jar",
          "url": "list-visualization-0.1-javadoc.jar",
          "size": 118928,
          "sha512": "43f2f817603ad7106045c0d197582f03267a4102496b3b6381ca6bed6b3ea66bb5ec558958d7c67be63b050f027912511694f0ded0c0b0f61151eddbb9bea882",
          "sha256": "3dc8d2683d67f0b23daaceaec1edb16599d4adef9302e74b1f76dbb7877bd1a1",
          "sha1": "76696797a5b73ca85161bcd53ea878b7a1dec9a7",
          "md5": "2f8d52791fb6678569379950d9203f20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "list-visualization-0.1-sources.jar",
          "url": "list-visualization-0.1-sources.jar",
          "size": 6162,
          "sha512": "831830b0d2b9e1f5aaa3f14c4687c59863decc6af2f85ddcca3bdd6d109327021e628ccccfdb8f728fd0e2135b957d90becd44142d49ae26cf6a1a990e8ec78b",
          "sha256": "ab3b5b1d7066859122562bc5e00ce1c4c781cc42b87352c77f3ffe54844ae6cd",
          "sha1": "58c7da8cc34ec55d4111c93f38b8de6e3ccb076b",
          "md5": "8c4d1110043ba6b3d2b38dafc48f7f0b"
        }
      ]
    }
  ]
}
