{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "vis-list-visualization",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vis-list-visualization-0.1.jar",
          "url": "vis-list-visualization-0.1.jar",
          "size": 13207,
          "sha512": "6f11e9094b000892195f05602ab75ef6d030f2c14943198651395ac46e98aa7132bafa12e489f1f66aa19829bea166fed384ce2249a5b1d3e88d56fcfc014340",
          "sha256": "fd8c7ae573d051013839e4a27398c20bedd39c6d3603b18bf973b3833d8e0f87",
          "sha1": "e09bc83e05406773f927763e442bd9844986e4e7",
          "md5": "bb3623b950972aa4641ea890f38b1c10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-frontend",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "vis-list-visualization-0.1.jar",
          "url": "vis-list-visualization-0.1.jar",
          "size": 13207,
          "sha512": "6f11e9094b000892195f05602ab75ef6d030f2c14943198651395ac46e98aa7132bafa12e489f1f66aa19829bea166fed384ce2249a5b1d3e88d56fcfc014340",
          "sha256": "fd8c7ae573d051013839e4a27398c20bedd39c6d3603b18bf973b3833d8e0f87",
          "sha1": "e09bc83e05406773f927763e442bd9844986e4e7",
          "md5": "bb3623b950972aa4641ea890f38b1c10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-list-visualization-0.1-javadoc.jar",
          "url": "vis-list-visualization-0.1-javadoc.jar",
          "size": 123308,
          "sha512": "851ef68b5eb7425c1eecb839039e5ea43e38aec80461f995e51f920429536f8508f0c1c85a0925d9847d2f678b2734a80b603cbbabcbace116c744a122d9a657",
          "sha256": "b7dd2a71ee125ac597475f908dacba2fdbf14e2376a8658ac550ef91e3603ed8",
          "sha1": "b8f1f59fa7e2231ed7ae2056bf54e665dd4eb9af",
          "md5": "70c27415e1bc01040e6046c53f8c81ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-list-visualization-0.1-sources.jar",
          "url": "vis-list-visualization-0.1-sources.jar",
          "size": 6407,
          "sha512": "cf41a9a5488ec9bd5a60f10df84261de188fcd189c849d94a7256294720c8ceb248a57c7d32e4d556808e829a2879d4819ba5dca3f17288b0bbd361b86efec11",
          "sha256": "2af7b1ca208e3f4aa76997da8c48e3cddc6bcc3f470086e3631f3124fa4eff72",
          "sha1": "94d177741e82abb1c8683eea78bc6e16f26e1ec2",
          "md5": "1be54207b19e613e164e8c85d56f71d5"
        }
      ]
    }
  ]
}
