{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis.core",
    "module": "bugvis-control",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bugvis-control-0.1.jar",
          "url": "bugvis-control-0.1.jar",
          "size": 56577,
          "sha512": "d428b6a4ea23f74ec0a6c35d0d0774d8b583c3fb4f5d0659021163851bcf0be47373d52df59161eea6a3a174756480cf7d37d6af4ac8fdc7b4f85183cafddccc",
          "sha256": "f27c52ea46b3acb4d4ac2ff46c38ff97b4f81944328f3704ff814ac289845b03",
          "sha1": "c7d22e3ac830caccfbfdd51039bf0f10dfb52b68",
          "md5": "fcf3a9628ff1c5f3c5ce7f1cf73ef557"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis.core",
          "module": "bugvis-model",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-control-0.1.jar",
          "url": "bugvis-control-0.1.jar",
          "size": 56577,
          "sha512": "d428b6a4ea23f74ec0a6c35d0d0774d8b583c3fb4f5d0659021163851bcf0be47373d52df59161eea6a3a174756480cf7d37d6af4ac8fdc7b4f85183cafddccc",
          "sha256": "f27c52ea46b3acb4d4ac2ff46c38ff97b4f81944328f3704ff814ac289845b03",
          "sha1": "c7d22e3ac830caccfbfdd51039bf0f10dfb52b68",
          "md5": "fcf3a9628ff1c5f3c5ce7f1cf73ef557"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-control-0.1-javadoc.jar",
          "url": "bugvis-control-0.1-javadoc.jar",
          "size": 200895,
          "sha512": "ad798d28d8aa815b49b8d1215553d6c6ae5de3029e729379853985bca199858f10942f18273d066a2cb398c81920613b03949f975c2c4f61bf361302f435c413",
          "sha256": "95f45e3795e7a1095ae14ee671ab8018dadb71f04bdb2501a6ffc5a476fb50a2",
          "sha1": "3392ca12cf279cd6e446fb7e023d8bff9a199a41",
          "md5": "b2abb120114570e24d2aca632b720028"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-control-0.1-sources.jar",
          "url": "bugvis-control-0.1-sources.jar",
          "size": 28431,
          "sha512": "66db25100cca3cd91a5d6a8419a650c88c964f81fac96f2b4bfb5e5cd20972bdb514539903acb0130a64e3baea0206e4c362067df37a088b63d7fc83cbf61902",
          "sha256": "555c9459a6c1d11f642afd2682efccd25793f061a556dbb66bd1caa4d3feff81",
          "sha1": "d489f1815ebfc8655864534c50dfa66f2f1ca5e5",
          "md5": "d97e3f4fffcf053bb5fed7ef380d539b"
        }
      ]
    }
  ]
}
