{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "vis-u03-graph",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1.jar",
          "url": "vis-u03-graph-0.1.jar",
          "size": 27628,
          "sha512": "92e90701a9a457b91e0fc606c2d02dfce10930b9b41edcd124079c506cab46ef00daf6d00198871de5d0deff9365df9b13ee1fb358a593df53bd082f351ffac7",
          "sha256": "3334798907d9b437a7909aff586fd5b0489314f35960af1bd4f5c0524b4e19f4",
          "sha1": "5afc2064da722e82d48382b0ab694da8e1aac3db",
          "md5": "c45ae2821ac970e25faff09a1d569dc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-frontend",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "vis-u03-graph-0.1.jar",
          "url": "vis-u03-graph-0.1.jar",
          "size": 27628,
          "sha512": "92e90701a9a457b91e0fc606c2d02dfce10930b9b41edcd124079c506cab46ef00daf6d00198871de5d0deff9365df9b13ee1fb358a593df53bd082f351ffac7",
          "sha256": "3334798907d9b437a7909aff586fd5b0489314f35960af1bd4f5c0524b4e19f4",
          "sha1": "5afc2064da722e82d48382b0ab694da8e1aac3db",
          "md5": "c45ae2821ac970e25faff09a1d569dc0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1-javadoc.jar",
          "url": "vis-u03-graph-0.1-javadoc.jar",
          "size": 139415,
          "sha512": "46e5de0e6cf038588a2fc7531feb562584cae263eadd4739093a502ae7f3118ceff97b23c24415976002ac9840536fd5d3add28fdaa8d6151ad7b114b4734d18",
          "sha256": "b50b60bf85f6ce4b1c4f51538b008ba7868cd4d5507665c139226814adc065d3",
          "sha1": "774f75884bedecd10d6f4c7dd7cc83c6aab2ce88",
          "md5": "32a7d7ae49342300f809e5f5afe8f9dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1-sources.jar",
          "url": "vis-u03-graph-0.1-sources.jar",
          "size": 12507,
          "sha512": "f28e1e640c0e7078229d0860ee0435594538822761ed5bb4c852f268b37850769613eb5c5e5fb39c4da71efa65459113a9e9fe0dfc168050fb9aef247ec1ab17",
          "sha256": "0a48f14cc1669da812f036f7ebe83786421f83560510fb0593cead8c05822b31",
          "sha1": "41de05c0d14d4712be28586aef8a79ebce544d39",
          "md5": "11c11e0713d56aae649e62dc94663738"
        }
      ]
    }
  ]
}
