{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "bugvis-model",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-instr-api",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-model-0.1.jar",
          "url": "bugvis-model-0.1.jar",
          "size": 89162,
          "sha512": "e4193634f30c152e31fa0e795214ccd8fcdb31662ecd07d7765200ebb0a5725bc88f00c459a35f843ff26ffe1bb694f84d405709234ee42138b88bbf87a12f9f",
          "sha256": "d06f48d1f4ea6033821d98d2222ccd8a16c1249c970e08edbc2c995c21a6d368",
          "sha1": "4b7f130dc364e6237fc1587a9ab544d3a6744858",
          "md5": "449ef966ddf934fa0e8b9e80f540c48c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-instr-api",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-model-0.1.jar",
          "url": "bugvis-model-0.1.jar",
          "size": 89162,
          "sha512": "e4193634f30c152e31fa0e795214ccd8fcdb31662ecd07d7765200ebb0a5725bc88f00c459a35f843ff26ffe1bb694f84d405709234ee42138b88bbf87a12f9f",
          "sha256": "d06f48d1f4ea6033821d98d2222ccd8a16c1249c970e08edbc2c995c21a6d368",
          "sha1": "4b7f130dc364e6237fc1587a9ab544d3a6744858",
          "md5": "449ef966ddf934fa0e8b9e80f540c48c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-model-0.1-javadoc.jar",
          "url": "bugvis-model-0.1-javadoc.jar",
          "size": 372177,
          "sha512": "40ab02f7b6a6a161834dfe231740eff1eec1355903bd615d1e637b685075be682112b2dbee28a2ec610596ae78fe441244f4f1a9772a0f0cc77306b21c7aab46",
          "sha256": "3fbd5fc84a355af791243319064389a3aea94a62eb16776bff710013245857c3",
          "sha1": "15296834704dad4805b01e81b0c195f503c9080b",
          "md5": "6744e9135946c149af755e6c3993b0ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-model-0.1-sources.jar",
          "url": "bugvis-model-0.1-sources.jar",
          "size": 50020,
          "sha512": "bf117237438b11aff7317285dc9af70eb0f0a704bd340e9cbcbb130f88f81122d39f842d3ebc8272a470fcbdc88f48589e0e6e4650aa3d61a19d2340f447b6fc",
          "sha256": "308fc4651c44a1611e1f5fa6793891de5ba18283411f6b0196aa887fec23e690",
          "sha1": "9c17ca34bdfc1748f0af3351cd11089afefde234",
          "md5": "444e38844e5bcd5398a86d7e8201a549"
        }
      ]
    }
  ]
}
