{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "vis-u03-graph",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1.jar",
          "url": "vis-u03-graph-0.1.jar",
          "size": 27634,
          "sha512": "a3e790e6c93fa9f9ccdf55093751b0b9462bac849d67807cd1f1bb388edc51c563585f50177d870227fc8268fad7ef03099eab7b966d0433ed79c4a52f041d03",
          "sha256": "99e8eb0338bfcf4310bcd858c170f31566a572316a2bdada19b92b28fcb76de4",
          "sha1": "e5a8e29da0bd470d74a9c0b6fde99ea4321f8f61",
          "md5": "a7866587d8bf48f75bc1f1d6d2770bff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-frontend",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "vis-u03-graph-0.1.jar",
          "url": "vis-u03-graph-0.1.jar",
          "size": 27634,
          "sha512": "a3e790e6c93fa9f9ccdf55093751b0b9462bac849d67807cd1f1bb388edc51c563585f50177d870227fc8268fad7ef03099eab7b966d0433ed79c4a52f041d03",
          "sha256": "99e8eb0338bfcf4310bcd858c170f31566a572316a2bdada19b92b28fcb76de4",
          "sha1": "e5a8e29da0bd470d74a9c0b6fde99ea4321f8f61",
          "md5": "a7866587d8bf48f75bc1f1d6d2770bff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1-javadoc.jar",
          "url": "vis-u03-graph-0.1-javadoc.jar",
          "size": 139415,
          "sha512": "46e5de0e6cf038588a2fc7531feb562584cae263eadd4739093a502ae7f3118ceff97b23c24415976002ac9840536fd5d3add28fdaa8d6151ad7b114b4734d18",
          "sha256": "b50b60bf85f6ce4b1c4f51538b008ba7868cd4d5507665c139226814adc065d3",
          "sha1": "774f75884bedecd10d6f4c7dd7cc83c6aab2ce88",
          "md5": "32a7d7ae49342300f809e5f5afe8f9dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1-sources.jar",
          "url": "vis-u03-graph-0.1-sources.jar",
          "size": 12500,
          "sha512": "13f6a98241a05cec0c9b8ac5ffae8b342b770215ea1b852b29d2f8046480abeb2fee54fc265acbbc487da7ca7834435f5655982416d4daf65c2150fa5574e057",
          "sha256": "f497a2bc181888224d8db4013524c5837b2afa2649a605c9061f3bf4f1918ce8",
          "sha1": "e59119ba2080bcc4365d4998ffe3355795ebf8a6",
          "md5": "d81b97ff4716a1ad26841145ae9af3c3"
        }
      ]
    }
  ]
}
