{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "vis-u03-graph",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1.jar",
          "url": "vis-u03-graph-0.1.jar",
          "size": 25756,
          "sha512": "38ae15c03a236fd6a76356e2845ed9378dcc29b922a44b501b3189b84224952c74d76c01f8af421a97f7f2883a86c7214f7016d7db638123e1cf338846878680",
          "sha256": "618dcd4c2cb64bf062d59053beaa71b72160c9d034f7afd4386e9d9ddc60af94",
          "sha1": "0bcdb11ebb38f1d10856e56aceb2ccfddc9084c8",
          "md5": "7e48740c153c84960985193029189003"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-frontend",
          "version": {
            "requires": "0.1"
          }
        }
      ],
      "files": [
        {
          "name": "vis-u03-graph-0.1.jar",
          "url": "vis-u03-graph-0.1.jar",
          "size": 25756,
          "sha512": "38ae15c03a236fd6a76356e2845ed9378dcc29b922a44b501b3189b84224952c74d76c01f8af421a97f7f2883a86c7214f7016d7db638123e1cf338846878680",
          "sha256": "618dcd4c2cb64bf062d59053beaa71b72160c9d034f7afd4386e9d9ddc60af94",
          "sha1": "0bcdb11ebb38f1d10856e56aceb2ccfddc9084c8",
          "md5": "7e48740c153c84960985193029189003"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1-javadoc.jar",
          "url": "vis-u03-graph-0.1-javadoc.jar",
          "size": 133243,
          "sha512": "f73deb0acde1817917174b747dd5ed5d547eb9b768db98d10e2cc0ad64b425e6cf7427ac1b4457be0400b360adfd3bd424ae0f9e53b8bbafe9fd6c0f51aff566",
          "sha256": "a19b8bacd1b4c69aa67006af5a40b8c2ed43f6cded69c2f6b9067061b8172a33",
          "sha1": "ce1b3f1667abeeb25f0447fb08cb9ae4d577aa27",
          "md5": "40f7c4321d82f9f236bcc4929cbc0e38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vis-u03-graph-0.1-sources.jar",
          "url": "vis-u03-graph-0.1-sources.jar",
          "size": 11744,
          "sha512": "de35dc9abb902a67fd2e4d5a65ed1631794a6a6bc05675dcb2b3ffd585b8d4d162191d13832606afc9e70e3414a5c5a09df22acc54fba0e828e98a86d7341200",
          "sha256": "644b0f27f5f14f033f96fb71827e48d32a6cb9d79251fe8c9213e12037786a3e",
          "sha1": "faee41e7edf8a7dbe026fb97d0454e55b5031eca",
          "md5": "0db93044b023ac3bae9953edddce4a3c"
        }
      ]
    }
  ]
}
