{
  "formatVersion": "1.1",
  "component": {
    "group": "de.unibwm.inf2.bugvis",
    "module": "bugvis-instrumenter",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bugvis-instrumenter-0.1.jar",
          "url": "bugvis-instrumenter-0.1.jar",
          "size": 212504,
          "sha512": "d0b12581cd72765435bcf3194a866a7df3cd1582b1594635e5a608efe2ec3abda7d568874dc482bc5291b0a0c4c454696a597359447052fecc7bf42b8217aebb",
          "sha256": "ba1bfc6011dc7fa5e0365d055c5017f0d129ab3346d39d1b0320ac25ae030981",
          "sha1": "949b557304f20e9b3047d5a9327dbce4f0986b9c",
          "md5": "c719d7ae6ec97e68052f8f6522b7c889"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.37"
          }
        },
        {
          "group": "de.unibwm.inf2.bugvis",
          "module": "bugvis-instr-api",
          "version": {
            "requires": "0.1"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "bugvis-instrumenter-0.1.jar",
          "url": "bugvis-instrumenter-0.1.jar",
          "size": 212504,
          "sha512": "d0b12581cd72765435bcf3194a866a7df3cd1582b1594635e5a608efe2ec3abda7d568874dc482bc5291b0a0c4c454696a597359447052fecc7bf42b8217aebb",
          "sha256": "ba1bfc6011dc7fa5e0365d055c5017f0d129ab3346d39d1b0320ac25ae030981",
          "sha1": "949b557304f20e9b3047d5a9327dbce4f0986b9c",
          "md5": "c719d7ae6ec97e68052f8f6522b7c889"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-instrumenter-0.1-sources.jar",
          "url": "bugvis-instrumenter-0.1-sources.jar",
          "size": 86281,
          "sha512": "597ac7e217779f8f9738f34151eabe475a598fddadf2641cddad70bc0c8e48a138920d580f8a34c7d4aa93c39946bd449455fb8110fc6c228a8fddd577385148",
          "sha256": "fe0b29f33bda5efca4d7e4209913dc00e211e5ba757aacb2ffc434818e5c18a6",
          "sha1": "7374ae8aa7df2d806ae1550d9aad3d55a6dcff7c",
          "md5": "d9bcf0016d70f00bf707cdbe25e56678"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bugvis-instrumenter-0.1-javadoc.jar",
          "url": "bugvis-instrumenter-0.1-javadoc.jar",
          "size": 386490,
          "sha512": "42518213592469ffa2bef73aca71c2c12880bbd74fd7b32ca9c71495d69b8d3307cda18600cac03e7ec3890a00d347ee89fadf20dafc92e411e907c7e7218c93",
          "sha256": "34e8171f0e08c3a5180f7208a51487fde2566ab87658ed12d231e46c5e24f92a",
          "sha1": "7fbdf339f9486cf009141a46c9cb12e59752444d",
          "md5": "8cf8f746512af226bfe8e31c7ab36bff"
        }
      ]
    }
  ]
}
